"""baseline schema

Revision ID: 3090a68e02d4
Revises: 
Create Date: 2026-09-05 08:52:18.277865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3090a68e02d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambling_seasons',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('IN_PROGRESS', 'COMPLETE', name='gamblingseasonstate'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prop_bet_targets',
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_bet_targets_identifier'), 'prop_bet_targets', ['identifier'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gamblers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gambling_season_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambling_season_id'], ['gambling_seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parlays',
    sa.Column('gambling_season_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('slate_type', sa.Enum('TNF', 'FNF', 'MORNING_SLATE', 'AFTERNOON_SLATE', 'TD', 'SNF', 'MNF', 'INTERNATIONAL_GAME', 'SATURDAY', 'XMAS', 'WILDCARD', 'DIVISIONAL', 'CONFERENCE', name='slatetype'), nullable=False),
    sa.Column('competition_date', sa.Date(), nullable=False),
    sa.Column('state', sa.Enum('BUILDING', 'OPEN', 'CLOSED', name='parlaystate'), nullable=False),
    sa.Column('wager_pp', sa.Float(), nullable=False),
    sa.Column('payout_pp', sa.Float(), nullable=True),
    sa.Column('result', sa.Enum('WIN', 'LOSS', 'VOID', 'BOZO', 'PUSH', name='parlayresult'), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambling_season_id'], ['gambling_seasons.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['gamblers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picks',
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('prop_bet_target_id', sa.Integer(), nullable=False),
    sa.Column('prop_type', sa.Enum('TARGETS', 'FGS', 'LONGEST_RUSH', 'PASS_ATTEMPTS', 'RUSH_YDS', 'REC_YDS', 'RUSH_ATTEMPTS', 'TACKLES_ASSISTS', 'RUSH_REC_YDS', 'LONGEST_RECEPTION', 'LONGEST_TD', 'PASSING_TDS', 'PASSING_INTS', 'PASSING_YDS', 'TDS', 'RECEPTIONS', 'LONGEST_COMPLETION', 'PASS_COMPLETIONS', 'SACKS', name='propbettype'), nullable=False),
    sa.Column('parlay_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('corrected_line', sa.Float(), nullable=True),
    sa.Column('direction', sa.Enum('OVER', 'UNDER', name='propbetdirection'), nullable=False),
    sa.Column('sauce_factor', sa.Enum('BITCH', 'SPICY', name='saucefactor'), nullable=True),
    sa.Column('result', sa.Enum('WIN', 'LOSS', 'VOID', 'BOZO', 'PUSH', name='pickresult'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.ForeignKeyConstraint(['parlay_id'], ['parlays.id'], ),
    sa.ForeignKeyConstraint(['prop_bet_target_id'], ['prop_bet_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick_vetoes',
    sa.Column('pick_id', sa.Integer(), nullable=False),
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'UNDECIDED', name='vetoapprovalstatus'), nullable=False),
    sa.Column('result', sa.Enum('GOOD', 'BAD', 'VOID', 'PUSH', 'BOZO_SAVER', 'BOZO', name='vetoresult'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veto_votes',
    sa.Column('veto_id', sa.Integer(), nullable=False),
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('affirmative', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.ForeignKeyConstraint(['veto_id'], ['pick_vetoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veto_votes')
    op.drop_table('pick_vetoes')
    op.drop_table('picks')
    op.drop_table('parlays')
    op.drop_table('gamblers')
    op.drop_table('users')
    op.drop_index(op.f('ix_prop_bet_targets_identifier'), table_name='prop_bet_targets')
    op.drop_table('prop_bet_targets')
    op.drop_table('gambling_seasons')
    # ### end Alembic commands ###
