"""feedback rating direction

Revision ID: 51247c0ad3b9
Revises: fe2be331075f
Create Date: 2026-09-07 20:06:28.131537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51247c0ad3b9'
down_revision: Union[str, Sequence[str], None] = 'fe2be331075f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_ratings', sa.Column('value', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_ratings', 'value')
    # ### end Alembic commands ###
