"""add pick reactions and comments

Revision ID: 64d92b883638
Revises: 1261d816f03b
Create Date: 2026-09-07 21:33:57.456322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d92b883638'
down_revision: Union[str, Sequence[str], None] = '1261d816f03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick_comments',
    sa.Column('pick_id', sa.Integer(), nullable=False),
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick_reactions',
    sa.Column('pick_id', sa.Integer(), nullable=False),
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pick_id', 'gambler_id', 'emoji', name='uq_pick_reaction_gambler_emoji')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick_reactions')
    op.drop_table('pick_comments')
    # ### end Alembic commands ###
