"""add espn athlete id to prop bet targets

Revision ID: 9b52c6f801e7
Revises: f76b902850e7
Create Date: 2026-09-08 20:07:52.860015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b52c6f801e7'
down_revision: Union[str, Sequence[str], None] = '64d92b883638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prop_bet_targets', sa.Column('espn_athlete_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prop_bet_targets', 'espn_athlete_id')
    # ### end Alembic commands ###
