"""add season long picks

Revision ID: ab3d44bb7c94
Revises: 4e069622d8b9
Create Date: 2026-09-06 09:39:33.024498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ab3d44bb7c94'
down_revision: Union[str, Sequence[str], None] = '4e069622d8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Only seasonpickkind is new. The other two are already in the database from the picks
# table, so they are referenced with create_type=False — otherwise create_table emits a
# second CREATE TYPE and the migration dies on "type already exists".
season_pick_kind = postgresql.ENUM("PLAYER_PROP", "TEAM_WINS", name="seasonpickkind", create_type=False)
existing_prop_bet_type = postgresql.ENUM(name="propbettype", create_type=False)
existing_prop_bet_direction = postgresql.ENUM(name="propbetdirection", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    season_pick_kind.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_picks',
    sa.Column('gambling_season_id', sa.Integer(), nullable=False),
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('kind', season_pick_kind, nullable=False),
    sa.Column('prop_bet_target_id', sa.Integer(), nullable=False),
    sa.Column('prop_type', existing_prop_bet_type, nullable=True),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('direction', existing_prop_bet_direction, nullable=False),
    sa.Column('is_finalized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.ForeignKeyConstraint(['gambling_season_id'], ['gambling_seasons.id'], ),
    sa.ForeignKeyConstraint(['prop_bet_target_id'], ['prop_bet_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_pick_weeks',
    sa.Column('season_pick_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_pick_id'], ['season_picks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_pick_id', 'week', name='uq_season_pick_week')
    )
    op.add_column('gamblers', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamblers', 'is_admin')
    op.drop_table('season_pick_weeks')
    op.drop_table('season_picks')
    # Dropping a table leaves its enum type behind, which would break the next upgrade.
    season_pick_kind.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
