"""add feedback

Revision ID: fe2be331075f
Revises: 515b5d6d8025
Create Date: 2026-09-07 19:02:44.837393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2be331075f'
down_revision: Union[str, Sequence[str], None] = '515b5d6d8025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('addressed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_comments',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_ratings',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('gambler_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['gambler_id'], ['gamblers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id', 'gambler_id', name='uq_feedback_rating_gambler')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_ratings')
    op.drop_table('feedback_comments')
    op.drop_table('feedback')
    # ### end Alembic commands ###
